// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lunara/LunaraMomentsAtlas.tsx": () => import("../components/mockups/lunara/LunaraMomentsAtlas.tsx"),
  "./components/mockups/lunara/LunaraMomentsConstellation.tsx": () => import("../components/mockups/lunara/LunaraMomentsConstellation.tsx"),
  "./components/mockups/lunara/LunaraMomentsLedger.tsx": () => import("../components/mockups/lunara/LunaraMomentsLedger.tsx"),
  "./components/mockups/lunara/LunaraMomentsMoonTimeline.tsx": () => import("../components/mockups/lunara/LunaraMomentsMoonTimeline.tsx")
};
